on:
  push:
    branches:
      - master
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/bookdown.yaml'
  pull_request:
    branches: [main, master]
    paths:
      - 'docs/**'
      - '.github/workflows/bookdown.yaml'
  workflow_dispatch:
    inputs:
      publish:
        description: 'publish the book to github pages for connect cloud deployment'
        required: false
        default: false
        type: boolean

name: Build and deploy book

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KNITR_OPTIONS: "knitr.chunk.tidy=TRUE"
    steps:
      - name: Checkout repo
        uses: actions/checkout@HEAD

      - name: Setup R
        uses: r-lib/actions/setup-r@HEAD

      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@HEAD
        with:
          pandoc-version: '2.11.4'

      - name: Install TinyTeX
        uses: r-lib/actions/setup-tinytex@HEAD
        env:
          # install full prebuilt version
          TINYTEX_INSTALLER: TinyTeX

      - name: Install OS dependencies
        run: |
          brew install --cask xquartz
          brew install --cask calibre

      - uses: r-lib/actions/setup-r-dependencies@HEAD
        with:
          extra-packages: local::.
          needs: book

      - name: Cache bookdown results
        uses: actions/cache@HEAD
        with:
          path: docs/_bookdown_files
          key: bookdown-1-${{ hashFiles('docs/*Rmd') }}
          restore-keys: bookdown-1-

      - name: Build all book
        run: make -C docs all

      - name: Deploy Gitbook to gh-pages
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/_book
          clean: true
          single-commit: true
          dry-run: ${{ (github.event_name == 'workflow_dispatch' && (github.event.inputs.publish == 'false' || github.event.inputs.publish == false)) || false }}

      - name: Upload book folder for debug
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: book-dir
          path: docs
